build: false

environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python37"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - "curl -fsS -o C:/get-pip.py https://bootstrap.pypa.io/get-pip.py"
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe install -U setuptools"
  - "%PYTHON%/python.exe setup.py develop"
  - "%PYTHON%/Scripts/pip.exe install -U -r requirements.txt"

test_script:
  - "%PYTHON%/python.exe -m flake8"
  - "%PYTHON%/Scripts/py.test.exe -sv"
